# Generated by Django 5.1.2 on 2024-11-01 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0004_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ("title",), "verbose_name_plural": "Categories"},
        ),
    ]
