# Generated by Django 5.1.2 on 2024-11-01 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0005_alter_category_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="posts",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="blogs.category",
            ),
            preserve_default=False,
        ),
    ]
