# Generated by Django 5.1.2 on 2024-11-01 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0006_post_posts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="posts",
        ),
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="blogs.category",
            ),
            preserve_default=False,
        ),
    ]
