# Generated by Django 5.1.2 on 2024-11-01 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0007_remove_post_posts_post_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
