# Generated by Django 5.1.2 on 2024-11-01 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0008_remove_post_category_delete_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="author_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="post",
            name="author_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
